Repository tektoncd/mcp-server, pull requests merged in 2025-04, with the labels that each got.

#7 add ci and go mod
  .github/workflows/chatops_retest.yaml
  .github/workflows/ci.yaml
  .github/workflows/slash.yml
  .gitignore
  cmd/tekton-mcp-server/main.go
  go.mod
Labels: size/L

#12 Update golangci-lint to v2.1.2
  .github/workflows/ci.yaml
  .golangci.yml
  internal/tools/start.go
Labels: size/L

#13 .github: add a dependabot configuration
  .github/dependabot.yml
Labels: size/S

#14 Add ResourceTemplate from openshift-pipelines/mcp-tekton
  cmd/tekton-mcp-server/main.go
  internal/resources/resources.go
  internal/tools/tools.go
Labels: size/L

#18 Implement SSE transport
  cmd/tekton-mcp-server/main.go
Labels: approved, lgtm, size/M
